/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <GA_SENSORP.h>
#include <GA_SENSORP_aliases.h>
#include <ADC_SAR.h>
#include <GA_SENSORN.h>
#include <GA_SENSORN_aliases.h>
#include <IR_DRIVE.h>
#include <IR_DRIVE_aliases.h>
#include <NIR_DRIVE1.h>
#include <NIR_DRIVE1_aliases.h>
#include <UART_DEB.h>
#include <UART_DEB_SPI_UART.h>
#include <UART_DEB_PINS.h>
#include <UART_DEB_SPI_UART_PVT.h>
#include <UART_DEB_PVT.h>
#include <UART_DEB_BOOT.h>
#include <Clock_1.h>
#include <PWM_GREEN.h>
#include <PWM_IR_AND_RED.h>
#include <NIR_DRIVE2.h>
#include <NIR_DRIVE2_aliases.h>
#include <GREEN_DRIVE.h>
#include <GREEN_DRIVE_aliases.h>
#include <Opamp.h>
#include <GA_SENSOR_OUT.h>
#include <GA_SENSOR_OUT_aliases.h>
#include <RED_DRIVE.h>
#include <RED_DRIVE_aliases.h>
#include <PWM_NIR1.h>
#include <ADC_IN.h>
#include <ADC_IN_aliases.h>
#include <ADC_SAR_IRQ.h>
#include <ADC_SAR_intClock.h>
#include <UART_DEB_SCBCLK.h>
#include <UART_DEB_tx.h>
#include <UART_DEB_tx_aliases.h>
#include <UART_DEB_SCB_IRQ.h>
#include <UART_DEB_rx.h>
#include <UART_DEB_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

